RZR-140: Correct the display of pop-up with pictures in the gallery
ST-CORE/rzrsite-ui pull request #58
Opened 2023-06-07 08:36 UTC by sweetharwest

2023-06-08 03:22 UTC, cashidze requested changes

2023-06-08 03:22 UTC, cashidze commented on src/components/shared/modal-picture/modal-picture.scss
> +    bottom: 8%;
Выражение "bottom" врятли что-то действительно меняет

2023-06-08 03:22 UTC, cashidze commented on src/components/shared/modal-picture/modal-picture.scss
> +    bottom: 0;
"bottom" можно убрать, я думаю

2023-06-08 03:22 UTC, cashidze commented on src/components/shared/modal-picture/modal-picture.tsx
> +                        {description}
Мы пропускаем HTML здесь?

2023-06-08 03:22 UTC, cashidze commented on src/components/shared/modal-picture/modal-picture.scss
> +   .close-picture {
название класса сомнительное. я бы сделал crosshair-area или crosshair-container

2023-06-08 03:22 UTC, cashidze commented on src/components/shared/modal-picture/modal-picture.scss
> +    width: 96%;
96% ? почему?

2023-06-08 15:27 UTC, sweetharwest commented on src/components/shared/modal-picture/modal-picture.tsx
> +                        {description}
да, но размеры блока не очень гибкие

2023-06-08 15:27 UTC, sweetharwest commented on src/components/shared/modal-picture/modal-picture.scss
> +    bottom: 0;
если его убрать то footer улетает наверх

2023-06-08 15:28 UTC, sweetharwest commented on src/components/shared/modal-picture/modal-picture.scss
> +    bottom: 8%;
если его убрать то footer улетает наверх

2023-06-08 15:29 UTC, sweetharwest commented on src/components/shared/modal-picture/modal-picture.scss
> +   .close-picture {
поменял

2023-06-08 15:30 UTC, sweetharwest commented on src/components/shared/modal-picture/modal-picture.scss
> +    width: 96%;
поменял на 92%: 4% под крестик 4% с другой стороны

2023-06-09 20:15 UTC, cashidze approved these changes

2023-06-09 20:18 UTC, merged